spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://projects-db.ewi.tudelft.nl:3306/projects_OOPPGroup4
    username: pu_OOPPGroup4
    password: cg5EQkKNHN08
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true