package nl.tudelft.oopp.controllers;

import nl.tudelft.oopp.entities.Type;
import nl.tudelft.oopp.repositories.TypeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;

@EnableJpaRepositories("nl.tudelft.oopp.repositories")


@Controller
public class TypeController {

    @Autowired
    private TypeRepository typeRepository;

    /*
    Allows us to insert a new Type tuple into the database. As its ID is autogenerated, we make use of HTTP Post
    request to do so.
     */
    @PostMapping("/addType")
    @ResponseBody
    public Type addTypeToDB(@RequestBody Type type) {
        Type newtype = type;
        System.out.println("Adding a new Type to the DB: " + newtype.toString());
        return typeRepository.save(newtype);
    }

    /*
    Method returns a list of all the tuples of the Type table.
     */
    @GetMapping("/getListOfTypes")
    @ResponseBody
    public List<Type> getListOfTypes() {
        return typeRepository.findAll();
    }

}
